name = input()
surname = input()
favorite = input()
zod = input()
print("Индивидуальный гороскоп для пользователя", name, surname)
print("Кем вы были в прошлой жизни:", favorite)
print("Ваш знак зодиака -", zod, ", поэтому вы - тонко чувствующая натура.")
